# Generated by Django 3.2.16 on 2026-07-31 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя участника')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия участника')),
                ('uni_id', models.SlugField(max_length=8, verbose_name='RSFID')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.SlugField(max_length=8, verbose_name='Слаг поле дисциплины')),
                ('name', models.CharField(max_length=25, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сходки')),
                ('date', models.DateField(verbose_name='Дата проведения сходки')),
                ('description', models.TextField(verbose_name='Описание сходки')),
                ('competitors', models.ManyToManyField(to='meet.Competitors', verbose_name='Участники сходки')),
            ],
            options={
                'verbose_name': 'Сходка',
                'verbose_name_plural': 'Сходки',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='RoundsOfDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.IntegerField(default=1, verbose_name='Количество раундов')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.discipline', verbose_name='Дисциплина')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.meet', verbose_name='Сходка')),
            ],
            options={
                'verbose_name': 'Раунд дисциплины',
                'verbose_name_plural': 'Раунды дисциплин',
            },
        ),
        migrations.AddField(
            model_name='meet',
            name='disciplines',
            field=models.ManyToManyField(through='meet.RoundsOfDiscipline', to='meet.Discipline', verbose_name='Дисциплины сходок'),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_1', models.CharField(default=0, max_length=15, verbose_name='Первая попытка')),
                ('attempt_2', models.CharField(default=0, max_length=15, verbose_name='Вторая попытка')),
                ('attempt_3', models.CharField(default=0, max_length=15, verbose_name='Третья попытка')),
                ('attempt_4', models.CharField(default=0, max_length=15, verbose_name='Четвертая попытка')),
                ('attempt_5', models.CharField(default=0, max_length=15, verbose_name='Пятая попытка')),
                ('average', models.CharField(default=0, max_length=15, verbose_name='Среднее время')),
                ('best', models.CharField(default=0, max_length=15, verbose_name='Лучшее время')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.competitors')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.discipline')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.meet')),
                ('round_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.roundsofdiscipline')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'unique_together': {('competitor', 'meet', 'discipline', 'round_number')},
            },
        ),
    ]
