# Generated by Django 3.2.16 on 2026-08-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_alter_results_round_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='results',
            unique_together=set(),
        ),
    ]
