# Generated by Django 3.2.16 on 2026-08-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_auto_20260802_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AddField(
            model_name='meet',
            name='locations',
            field=models.CharField(blank=True, default='ДВФУ', max_length=30),
        ),
        migrations.AlterField(
            model_name='results',
            name='average',
            field=models.CharField(default=0, max_length=15, verbose_name='Среднее'),
        ),
        migrations.AlterField(
            model_name='results',
            name='best',
            field=models.CharField(default=0, max_length=15, verbose_name='Лучшее'),
        ),
        migrations.AlterUniqueTogether(
            name='results',
            unique_together={('competitor', 'meet', 'discipline', 'round_number')},
        ),
    ]
