# Generated by Django 5.2.17 on 2026-08-21 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_auto_20260807_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_name', models.TextField(max_length=30, verbose_name='Название типов')),
            ],
        ),
        migrations.AlterField(
            model_name='meet',
            name='date',
            field=models.DateTimeField(verbose_name='Дата проведения сходки'),
        ),
        migrations.AlterField(
            model_name='meet',
            name='locations',
            field=models.CharField(blank=True, default='ДВФУ', max_length=30, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='meet',
            name='format_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meet.formattype'),
        ),
    ]
