# Generated by Django 5.2.17 on 2026-08-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_formattype_alter_meet_date_alter_meet_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formattype',
            name='format_name',
            field=models.CharField(max_length=30, verbose_name='Название типов'),
        ),
    ]
