# Generated by Django 5.2.17 on 2026-08-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_alter_formattype_format_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formattype',
            options={'verbose_name': 'Формат проведения', 'verbose_name_plural': 'Форматы проведения'},
        ),
    ]
