# Generated by Django 5.2.17 on 2026-08-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0007_alter_formattype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='format_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meet.formattype', verbose_name='Формат проведения'),
        ),
    ]
