# Generated by Django 5.2.17 on 2026-09-05 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0010_alter_results_average_alter_results_best'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='meet_files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt'])], verbose_name='Файл')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название файла')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='meet.meet', verbose_name='Соревнование')),
            ],
            options={
                'verbose_name': 'Файл соревнования',
                'verbose_name_plural': 'Файлы соревнований',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
