# Generated by Django 5.2.17 on 2026-09-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0012_alter_results_average_alter_results_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
