# Generated by Django 5.2.17 on 2026-09-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0014_resultformat_discipline_result_format'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultformat',
            options={'verbose_name': 'Формат результата', 'verbose_name_plural': 'Форматы результатов'},
        ),
    ]
