# Generated by Django 5.2.17 on 2026-08-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meet', '0007_alter_formattype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor', models.CharField(max_length=40, verbose_name='Имя Фамилия')),
                ('round_number', models.IntegerField(default=1, verbose_name='Номер раунда')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('attempt_1', models.CharField(default=0, max_length=15, verbose_name='Первая попытка')),
                ('attempt_2', models.CharField(default=0, max_length=15, verbose_name='Вторая попытка')),
                ('attempt_3', models.CharField(default=0, max_length=15, verbose_name='Третья попытка')),
                ('attempt_4', models.CharField(default=0, max_length=15, verbose_name='Четвертая попытка')),
                ('attempt_5', models.CharField(default=0, max_length=15, verbose_name='Пятая попытка')),
                ('average', models.CharField(default=0, max_length=15, verbose_name='Среднее')),
                ('best', models.CharField(default=0, max_length=15, verbose_name='Лучшее')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.discipline')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.meet')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'unique_together': {('competitor', 'meet', 'discipline', 'round_number')},
            },
        ),
    ]
