# Generated by Django 5.2.17 on 2026-08-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
        ('meet', '0008_alter_meet_format_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultscontest',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meet.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='resultscontest',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
