# Generated by Django 5.2.17 on 2026-08-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_resultscontest_discipline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultscontest',
            name='average',
            field=models.FloatField(default=0, verbose_name='Среднее'),
        ),
        migrations.AlterField(
            model_name='resultscontest',
            name='best',
            field=models.FloatField(default=0, verbose_name='Лучшее'),
        ),
    ]
