# Generated by Django 5.2.17 on 2026-08-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_alter_resultscontest_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultscontest',
            name='average',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Среднее'),
        ),
        migrations.AlterField(
            model_name='resultscontest',
            name='best',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Лучшее'),
        ),
    ]
