# Generated by Django 5.2.17 on 2026-09-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_alter_resultscontest_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultscontest',
            name='average',
            field=models.CharField(max_length=8, verbose_name='Среднее'),
        ),
        migrations.AlterField(
            model_name='resultscontest',
            name='best',
            field=models.CharField(max_length=8, verbose_name='Лучшее'),
        ),
    ]
